// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVGk6zBox0ZFxEEBTc1QkCnTm2z6kUxEw',
    appId: '1:766944778648:web:6945804a2b22037f2db3ed',
    messagingSenderId: '766944778648',
    projectId: 'kostion-fc656',
    authDomain: 'kostion-fc656.firebaseapp.com',
    storageBucket: 'kostion-fc656.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLp8k0q5ZVIFG2MY55CV6kVmGjzCi8RQ',
    appId: '1:766944778648:android:e7232ade97f9384e2db3ed',
    messagingSenderId: '766944778648',
    projectId: 'kostion-fc656',
    storageBucket: 'kostion-fc656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qTWVam8Vo00gO_khowAGsESeyxkyi2Y',
    appId: '1:766944778648:ios:5c13bb69bd2716ec2db3ed',
    messagingSenderId: '766944778648',
    projectId: 'kostion-fc656',
    storageBucket: 'kostion-fc656.appspot.com',
    iosBundleId: 'com.example.mamaRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qTWVam8Vo00gO_khowAGsESeyxkyi2Y',
    appId: '1:766944778648:ios:5c13bb69bd2716ec2db3ed',
    messagingSenderId: '766944778648',
    projectId: 'kostion-fc656',
    storageBucket: 'kostion-fc656.appspot.com',
    iosBundleId: 'com.example.mamaRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVGk6zBox0ZFxEEBTc1QkCnTm2z6kUxEw',
    appId: '1:766944778648:web:e0df1e990d1d6d572db3ed',
    messagingSenderId: '766944778648',
    projectId: 'kostion-fc656',
    authDomain: 'kostion-fc656.firebaseapp.com',
    storageBucket: 'kostion-fc656.appspot.com',
  );
}
